<?php

namespace PHPunctionBundle\Repository;

/**
 * ParkingPlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ParkingPlaceRepository extends \Doctrine\ORM\EntityRepository
{
}
