<?php

namespace PHPunctionBundle\Repository;

/**
 * TimeSlotRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TimeSlotRepository extends \Doctrine\ORM\EntityRepository
{
}
